#relative position between sensors

imu_to_gnss: [  1.00,  0.00,  0.00, 0.18,
                                0.00,  1.00, 0.00,  0.00,
                                0.00,  0.00,  1.00,  0.11,
                                0.00,  0.00,  0.00,  1.00]

imu_to_lidar: [  1.00,  0.00,  0.00,  0.42, 
                                0.00,  1.00,  0.00, -0.05,
                                0.00,  0.00,  1.00, -0.43,
                                0.00,  0.00,  0.00,  1.00]


imu_to_camera: [ 1.00,  0.00,  0.00,  0.00, 
                                      0.00,  1.00,  0.00,  0.00,
                                      0.00,  0.00,  1.00,  0.00,
                                      0.00,  0.00,  0.00,  0.00]

