#$ sensor  topic config
cloud_sub_topic: /velodyne_points   
imu_sub_topic: /imu/data 
gnss_fix_sub_topic:  /navsat/fix   
image_sub_topic: /

#$ sensors extrinsics
imu_to_gnss: [  1.00,  0.00,  0.00, 0.18,
                                0.00,  1.00, 0.00,  0.00,
                                0.00,  0.00,  1.00,  0.11,
                                0.00,  0.00,  0.00,  1.00]

imu_to_lidar: [  1.00,  0.00,  0.00,  0.42, 
                                0.00,  1.00,  0.00, -0.05,
                                0.00,  0.00,  1.00, -0.43,
                                0.00,  0.00,  0.00,  1.00]

imu_to_camera: [  1.00,  0.00,  0.00,  0.42, 
                                0.00,  1.00,  0.00, -0.05,
                                0.00,  0.00,  1.00, -0.43,
                                0.00,  0.00,  0.00,  1.00]

#$ sensors Intrinsics
lidar_intrinsics: 
    lidar_type: velodyne
    vertical_scan: 16               
    horizon_scan: 1800               
    downsample_size: 1                   
    lidar_minrange: 1.0                          
    lidar_maxrange: 1000.0          

imu_intrinsics:
  imu_acc_noise: 1.0e-03
  imu_gyr_noise: 1.0e-03
  imu_acc_bias_noise: 1.0e-05
  imu_gyr_bias_noise: 1.0e-05

camera_intrinsics:


gnss_intrinsics:
  gnss_enable: true                                             # if  use,set to "true"
  gnss_psr_std_thres: 2.0                               # pseudo-range std threshold
  gnss_dopp_std_thres: 2.0                           # doppler std threshold


#$ pcd map save
  pcd_save_enable: true
  pcd_save_directory: "/"                                 # default: "/" under glins->data 

#$ cpu param
cpu_param:
  cores: 4                                                                #cat /proc/cpuinfo | grep "core id" | sort | uniq | wc -l
  processor: 8                                                      #  cat /proc/cpuinfo | grep "processor" | sort | uniq | wc -l



#$ loop closure
loop_closure: 
  loop_closure_enable: true                            # if  use,set to "true"



#$ visualization


